package pe.edu.sistemas.sismatricula.domain;
// Generated 27/02/2018 02:20:40 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "modelomatriculafisi")
public class Alumno implements java.io.Serializable {

	private Integer idAlumno;
	private Periodo periodo;
	private String alumnoNombre;
	private String alumnoApellidos;
	private String alumnoCodigo;
	private String estado;
	private Set<Reactualizacion> reactualizacions = new HashSet<Reactualizacion>(0);

	public Alumno() {
	}

	public Alumno(Periodo periodo, String alumnoNombre, String alumnoApellidos, String alumnoCodigo, String estado,
			Set<Reactualizacion> reactualizacions) {
		this.periodo = periodo;
		this.alumnoNombre = alumnoNombre;
		this.alumnoApellidos = alumnoApellidos;
		this.alumnoCodigo = alumnoCodigo;
		this.estado = estado;
		this.reactualizacions = reactualizacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ALUMNO", unique = true, nullable = false)
	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		this.idAlumno = idAlumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ULTIMO_PERIODO")
	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@Column(name = "ALUMNO_NOMBRE", length = 45)
	public String getAlumnoNombre() {
		return this.alumnoNombre;
	}

	public void setAlumnoNombre(String alumnoNombre) {
		this.alumnoNombre = alumnoNombre;
	}

	@Column(name = "ALUMNO_APELLIDOS", length = 45)
	public String getAlumnoApellidos() {
		return this.alumnoApellidos;
	}

	public void setAlumnoApellidos(String alumnoApellidos) {
		this.alumnoApellidos = alumnoApellidos;
	}

	@Column(name = "ALUMNO_CODIGO", length = 45)
	public String getAlumnoCodigo() {
		return this.alumnoCodigo;
	}

	public void setAlumnoCodigo(String alumnoCodigo) {
		this.alumnoCodigo = alumnoCodigo;
	}

	@Column(name = "ESTADO", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alumno")
	public Set<Reactualizacion> getReactualizacions() {
		return this.reactualizacions;
	}

	public void setReactualizacions(Set<Reactualizacion> reactualizacions) {
		this.reactualizacions = reactualizacions;
	}

}
