package pe.edu.sistemas.sismatricula.domain;
// Generated 09/03/2018 02:41:50 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "modelomatriculafisi")
public class Alumno implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer idAlumno;
	private Periodo periodo;
	private String alumnoCodigo;
	private String alumnoAppaterno;
	private String alumnoApmaterno;
	private String alumnoNombre;
	private String alumnoEstado;
	private Integer alumnoIngreso;
	private Set<Tramite> tramites = new HashSet<Tramite>(0);

	public Alumno() {
	}

	public Alumno(Periodo periodo, String alumnoCodigo, String alumnoAppaterno, String alumnoApmaterno,
			String alumnoNombre, String alumnoEstado, Integer alumnoIngreso, Set<Tramite> tramites) {
		this.periodo = periodo;
		this.alumnoCodigo = alumnoCodigo;
		this.alumnoAppaterno = alumnoAppaterno;
		this.alumnoApmaterno = alumnoApmaterno;
		this.alumnoNombre = alumnoNombre;
		this.alumnoEstado = alumnoEstado;
		this.alumnoIngreso = alumnoIngreso;
		this.tramites = tramites;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ALUMNO", unique = true, nullable = false)
	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		this.idAlumno = idAlumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALUMNO_ULTIMO_PERIODO")
	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@Column(name = "ALUMNO_CODIGO", length = 45)
	public String getAlumnoCodigo() {
		return this.alumnoCodigo;
	}

	public void setAlumnoCodigo(String alumnoCodigo) {
		this.alumnoCodigo = alumnoCodigo;
	}

	@Column(name = "ALUMNO_APPATERNO", length = 45)
	public String getAlumnoAppaterno() {
		return this.alumnoAppaterno;
	}

	public void setAlumnoAppaterno(String alumnoAppaterno) {
		this.alumnoAppaterno = alumnoAppaterno;
	}

	@Column(name = "ALUMNO_APMATERNO", length = 45)
	public String getAlumnoApmaterno() {
		return this.alumnoApmaterno;
	}

	public void setAlumnoApmaterno(String alumnoApmaterno) {
		this.alumnoApmaterno = alumnoApmaterno;
	}

	@Column(name = "ALUMNO_NOMBRE", length = 45)
	public String getAlumnoNombre() {
		return this.alumnoNombre;
	}

	public void setAlumnoNombre(String alumnoNombre) {
		this.alumnoNombre = alumnoNombre;
	}

	@Column(name = "ALUMNO_ESTADO", length = 4)
	public String getAlumnoEstado() {
		if(this.alumnoEstado.equals("AC")){
			this.alumnoEstado="1";
		}
		if(this.alumnoEstado.equals("RSV")){
			this.alumnoEstado="2";
		}
		if(this.alumnoEstado.equals("INAC")){
			this.alumnoEstado="0";
		}
		return this.alumnoEstado;
	}

	public void setAlumnoEstado(String alumnoEstado) {
		this.alumnoEstado = alumnoEstado;
	}

	@Column(name = "ALUMNO_INGRESO")
	public Integer getAlumnoIngreso() {
		return this.alumnoIngreso;
	}

	public void setAlumnoIngreso(Integer alumnoIngreso) {
		this.alumnoIngreso = alumnoIngreso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alumno")
	public Set<Tramite> getTramites() {
		return this.tramites;
	}

	public void setTramites(Set<Tramite> tramites) {
		this.tramites = tramites;
	}

}
