package pe.edu.sistemas.sismatricula.domain;
// Generated 27/02/2018 02:20:40 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name = "periodo", catalog = "modelomatriculafisi")
public class Periodo implements java.io.Serializable {

	private Integer idPeriodo;
	private String periodoNombre;
	private Date periodoFechaIni;
	private Date periodoFechaFin;
	private Integer periodoValor;
	private Set<Reserva> reservasForIdPeriodoRetorno = new HashSet<Reserva>(0);
	private Set<Reactualizacion> reactualizacionsForIdPeriodoDejado = new HashSet<Reactualizacion>(0);
	private Set<Reactualizacion> reactualizacionsForIdPeriodoRetomado = new HashSet<Reactualizacion>(0);
	private Set<Alumno> alumnos = new HashSet<Alumno>(0);
	private Set<Reserva> reservasForIdPeriodoDejado = new HashSet<Reserva>(0);

	public Periodo() {
	}

	public Periodo(String periodoNombre, Date periodoFechaIni, Date periodoFechaFin, Integer periodoValor,
			Set<Reserva> reservasForIdPeriodoRetorno, Set<Reactualizacion> reactualizacionsForIdPeriodoDejado,
			Set<Reactualizacion> reactualizacionsForIdPeriodoRetomado, Set<Alumno> alumnos,
			Set<Reserva> reservasForIdPeriodoDejado) {
		this.periodoNombre = periodoNombre;
		this.periodoFechaIni = periodoFechaIni;
		this.periodoFechaFin = periodoFechaFin;
		this.periodoValor = periodoValor;
		this.reservasForIdPeriodoRetorno = reservasForIdPeriodoRetorno;
		this.reactualizacionsForIdPeriodoDejado = reactualizacionsForIdPeriodoDejado;
		this.reactualizacionsForIdPeriodoRetomado = reactualizacionsForIdPeriodoRetomado;
		this.alumnos = alumnos;
		this.reservasForIdPeriodoDejado = reservasForIdPeriodoDejado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PERIODO", unique = true, nullable = false)
	public Integer getIdPeriodo() {
		return this.idPeriodo;
	}

	public void setIdPeriodo(Integer idPeriodo) {
		this.idPeriodo = idPeriodo;
	}

	@Column(name = "PERIODO_NOMBRE", length = 45)
	public String getPeriodoNombre() {
		return this.periodoNombre;
	}

	public void setPeriodoNombre(String periodoNombre) {
		this.periodoNombre = periodoNombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PERIODO_FECHA_INI", length = 10)
	public Date getPeriodoFechaIni() {
		return this.periodoFechaIni;
	}

	public void setPeriodoFechaIni(Date periodoFechaIni) {
		this.periodoFechaIni = periodoFechaIni;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PERIODO_FECHA_FIN", length = 10)
	public Date getPeriodoFechaFin() {
		return this.periodoFechaFin;
	}

	public void setPeriodoFechaFin(Date periodoFechaFin) {
		this.periodoFechaFin = periodoFechaFin;
	}

	@Column(name = "PERIODO_VALOR")
	public Integer getPeriodoValor() {
		return this.periodoValor;
	}

	public void setPeriodoValor(Integer periodoValor) {
		this.periodoValor = periodoValor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodoByIdPeriodoRetorno")
	public Set<Reserva> getReservasForIdPeriodoRetorno() {
		return this.reservasForIdPeriodoRetorno;
	}

	public void setReservasForIdPeriodoRetorno(Set<Reserva> reservasForIdPeriodoRetorno) {
		this.reservasForIdPeriodoRetorno = reservasForIdPeriodoRetorno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodoByIdPeriodoDejado")
	public Set<Reactualizacion> getReactualizacionsForIdPeriodoDejado() {
		return this.reactualizacionsForIdPeriodoDejado;
	}

	public void setReactualizacionsForIdPeriodoDejado(Set<Reactualizacion> reactualizacionsForIdPeriodoDejado) {
		this.reactualizacionsForIdPeriodoDejado = reactualizacionsForIdPeriodoDejado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodoByIdPeriodoRetomado")
	public Set<Reactualizacion> getReactualizacionsForIdPeriodoRetomado() {
		return this.reactualizacionsForIdPeriodoRetomado;
	}

	public void setReactualizacionsForIdPeriodoRetomado(Set<Reactualizacion> reactualizacionsForIdPeriodoRetomado) {
		this.reactualizacionsForIdPeriodoRetomado = reactualizacionsForIdPeriodoRetomado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodo")
	public Set<Alumno> getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set<Alumno> alumnos) {
		this.alumnos = alumnos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodoByIdPeriodoDejado")
	public Set<Reserva> getReservasForIdPeriodoDejado() {
		return this.reservasForIdPeriodoDejado;
	}

	public void setReservasForIdPeriodoDejado(Set<Reserva> reservasForIdPeriodoDejado) {
		this.reservasForIdPeriodoDejado = reservasForIdPeriodoDejado;
	}

}
