package pe.edu.sistemas.sismatricula.domain;
// Generated 27/02/2018 02:20:40 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reactualizacion generated by hbm2java
 */
@Entity
@Table(name = "reactualizacion", catalog = "modelomatriculafisi")
public class Reactualizacion implements java.io.Serializable {

	private Integer idReactualizacion;
	private Alumno alumno;
	private Periodo periodoByIdPeriodoDejado;
	private Periodo periodoByIdPeriodoRetomado;
	private Date fechaSolicitudReactualizacion;

	public Reactualizacion() {
	}

	public Reactualizacion(Alumno alumno) {
		this.alumno = alumno;
	}

	public Reactualizacion(Alumno alumno, Periodo periodoByIdPeriodoDejado, Periodo periodoByIdPeriodoRetomado,
			Date fechaSolicitudReactualizacion) {
		this.alumno = alumno;
		this.periodoByIdPeriodoDejado = periodoByIdPeriodoDejado;
		this.periodoByIdPeriodoRetomado = periodoByIdPeriodoRetomado;
		this.fechaSolicitudReactualizacion = fechaSolicitudReactualizacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_REACTUALIZACION", unique = true, nullable = false)
	public Integer getIdReactualizacion() {
		return this.idReactualizacion;
	}

	public void setIdReactualizacion(Integer idReactualizacion) {
		this.idReactualizacion = idReactualizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALUMNO_ID_ALUMNO", nullable = false)
	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERIODO_DEJADO")
	public Periodo getPeriodoByIdPeriodoDejado() {
		return this.periodoByIdPeriodoDejado;
	}

	public void setPeriodoByIdPeriodoDejado(Periodo periodoByIdPeriodoDejado) {
		this.periodoByIdPeriodoDejado = periodoByIdPeriodoDejado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERIODO_RETOMADO")
	public Periodo getPeriodoByIdPeriodoRetomado() {
		return this.periodoByIdPeriodoRetomado;
	}

	public void setPeriodoByIdPeriodoRetomado(Periodo periodoByIdPeriodoRetomado) {
		this.periodoByIdPeriodoRetomado = periodoByIdPeriodoRetomado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_SOLICITUD_REACTUALIZACION", length = 10)
	public Date getFechaSolicitudReactualizacion() {
		return this.fechaSolicitudReactualizacion;
	}

	public void setFechaSolicitudReactualizacion(Date fechaSolicitudReactualizacion) {
		this.fechaSolicitudReactualizacion = fechaSolicitudReactualizacion;
	}

}
