package pe.edu.sistemas.sismatricula.domain;
// Generated 02/03/2018 05:00:38 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tramite generated by hbm2java
 */
@Entity
@Table(name = "tramite", catalog = "modelomatriculafisi")
public class Tramite implements java.io.Serializable {

	private Integer idTramite;
	private String tramiteTipo;
	private Date tramiteFechaIni;
	private Date tramiteFechaFin;
	private String tramitePeriodoIni;
	private String tramitePeriodoFin;
	private String tramiteRd;
	private int tramiteIdAlumno;

	public Tramite() {
	}

	public Tramite(int tramiteIdAlumno) {
		this.tramiteIdAlumno = tramiteIdAlumno;
	}

	public Tramite(String tramiteTipo, Date tramiteFechaIni, Date tramiteFechaFin, String tramitePeriodoIni,
			String tramitePeriodoFin, String tramiteRd, int tramiteIdAlumno) {
		this.tramiteTipo = tramiteTipo;
		this.tramiteFechaIni = tramiteFechaIni;
		this.tramiteFechaFin = tramiteFechaFin;
		this.tramitePeriodoIni = tramitePeriodoIni;
		this.tramitePeriodoFin = tramitePeriodoFin;
		this.tramiteRd = tramiteRd;
		this.tramiteIdAlumno = tramiteIdAlumno;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TRAMITE", unique = true, nullable = false)
	public Integer getIdTramite() {
		return this.idTramite;
	}

	public void setIdTramite(Integer idTramite) {
		this.idTramite = idTramite;
	}

	@Column(name = "TRAMITE_TIPO", length = 15)
	public String getTramiteTipo() {
		return this.tramiteTipo;
	}

	public void setTramiteTipo(String tramiteTipo) {
		this.tramiteTipo = tramiteTipo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TRAMITE_FECHA_INI", length = 10)
	public Date getTramiteFechaIni() {
		return this.tramiteFechaIni;
	}

	public void setTramiteFechaIni(Date tramiteFechaIni) {
		this.tramiteFechaIni = tramiteFechaIni;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TRAMITE_FECHA_FIN", length = 10)
	public Date getTramiteFechaFin() {
		return this.tramiteFechaFin;
	}

	public void setTramiteFechaFin(Date tramiteFechaFin) {
		this.tramiteFechaFin = tramiteFechaFin;
	}

	@Column(name = "TRAMITE_PERIODO_INI", length = 45)
	public String getTramitePeriodoIni() {
		return this.tramitePeriodoIni;
	}

	public void setTramitePeriodoIni(String tramitePeriodoIni) {
		this.tramitePeriodoIni = tramitePeriodoIni;
	}

	@Column(name = "TRAMITE_PERIODO_FIN", length = 45)
	public String getTramitePeriodoFin() {
		return this.tramitePeriodoFin;
	}

	public void setTramitePeriodoFin(String tramitePeriodoFin) {
		this.tramitePeriodoFin = tramitePeriodoFin;
	}

	@Column(name = "TRAMITE_RD", length = 45)
	public String getTramiteRd() {
		return this.tramiteRd;
	}

	public void setTramiteRd(String tramiteRd) {
		this.tramiteRd = tramiteRd;
	}

	@Column(name = "TRAMITE_ID_ALUMNO", nullable = false)
	public int getTramiteIdAlumno() {
		return this.tramiteIdAlumno;
	}

	public void setTramiteIdAlumno(int tramiteIdAlumno) {
		this.tramiteIdAlumno = tramiteIdAlumno;
	}

}
